# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  build:
    desc: Build for production
    cmds:
      - task: bashly
        vars:
          TASK_ARGS: generate --upgrade --env production

  docs:build:
    desc: Build documentation with Retype
    cmds:
      - task: retype
        vars:
          TASK_ARGS: build

  docs:start:
    desc: Build and serve documentation
    cmds:
      - task: retype
        vars:
          TASK_ARGS: start

  coding-standards:apply:
    desc: "Apply coding standards"
    cmds:
      - task: coding-standards:markdown:apply
      - task: coding-standards:yaml:apply

  coding-standards:check:
    desc: "Apply and check coding standards"
    cmds:
      - task: coding-standards:markdown:check
      - task: coding-standards:yaml:check
      - task: coding-standards:shell-script:check

  coding-standards:markdown:apply:
    desc: "Apply coding standards for Markdown"
    cmds:
      # Cf. .github/workflows/markdown.yaml
      - docker compose run --rm markdownlint markdownlint '**/*.md' --fix

  coding-standards:markdown:check:
    desc: "Apply and check coding standards for Markdown"
    cmds:
      - task: coding-standards:markdown:apply
      # Cf. .github/workflows/markdown.yaml
      - docker compose run --rm markdownlint markdownlint '**/*.md'

  coding-standards:shell-script:check:
    desc: "Check coding standards for shell scripts"
    cmds:
      # https://github.com/koalaman/shellcheck?tab=readme-ov-file#installing
      - docker run --rm --volume "$PWD:"/mnt koalaman/shellcheck:stable --external-sources {{.GLOB}}
    vars:
      # We use a block scalar (https://yaml-multiline.info/#block-scalars) here to make escaping (a little) easier.
      GLOB: >-
        {{.CLI_ARGS | default "src/*.sh" "src/lib/custom/*.sh"}}

  coding-standards:yaml:apply:
    desc: "Apply coding standards for YAML"
    cmds:
      # Cf. .github/workflows/yaml.yaml
      - docker compose run --rm prettier '**/*.{yml,yaml}' --write

  coding-standards:yaml:check:
    desc: "Apply and check coding standards for YAML"
    cmds:
      - task: coding-standards:yaml:apply
      # Cf. .github/workflows/yaml.yaml
      - docker compose run --rm prettier '**/*.{yml,yaml}' --check

  default:
    cmd: task --list
    silent: true

  bashly:
    internal: true
    cmds:
      # https://bashly.dev/installation/
      - docker pull dannyben/bashly
      - docker run --rm -it --user $(id -u):$(id -g) --volume "$PWD:/app" dannyben/bashly {{.TASK_ARGS}} {{.CLI_ARGS}}

  retype:
    internal: true
    cmds:
      - docker pull retypeapp/retype
      - docker run --rm -it --user $(id -u):$(id -g) --volume "$PWD:/retype" --publish '127.0.0.1:5001:5001' retypeapp/retype retype {{.TASK_ARGS}} {{.CLI_ARGS}}
